import type { editor } from "monaco-editor";

export const workspaceMonacoThemeLight = "vitesse-light";
export const workspaceMonacoThemeDark = "vitesse-dark";

const vitesseLightRules: editor.ITokenThemeRule[] = [
  { token: "keyword.operator", foreground: "ab5959" },
  { token: "keyword", foreground: "1e754f" },
  { token: "constant.language.boolean", foreground: "1e754f" },
  { token: "constant.language", foreground: "1e754f" },
  { token: "constant.numeric", foreground: "2f798a" },
  { token: "constant", foreground: "a65e2b" },
  { token: "string.regexp", foreground: "ab5e3f" },
  { token: "string.comment", foreground: "a0ada0" },
  { token: "string", foreground: "b56959" },
  { token: "support.type.builtin", foreground: "ab5959" },
  { token: "support.type", foreground: "2e8f82" },
  { token: "support.constant", foreground: "a65e2b" },
  { token: "support", foreground: "998418" },
  { token: "storage.type", foreground: "ab5959" },
  { token: "storage", foreground: "ab5959" },
  { token: "entity.name.function", foreground: "59873a" },
  { token: "entity.name.tag", foreground: "1e754f" },
  { token: "entity.name.type", foreground: "2e8f82" },
  { token: "entity.name", foreground: "59873a" },
  { token: "entity.other.attribute-name", foreground: "b07d48" },
  { token: "variable.language", foreground: "a65e2b" },
  { token: "variable", foreground: "b07d48" },
  { token: "type.identifier", foreground: "5a6aa6" },
  { token: "type", foreground: "2e8f82" },
  { token: "attribute.value", foreground: "b56959" },
  { token: "attribute.name", foreground: "998418" },
  { token: "meta.property-name", foreground: "998418" },
  { token: "meta.object-literal.key", foreground: "998418" },
  { token: "meta.module-reference", foreground: "1e754f" },
  { token: "property", foreground: "998418" },
  { token: "namespace", foreground: "b05a78" },
  { token: "delimiter.bracket", foreground: "999999" },
  { token: "delimiter", foreground: "999999" },
  { token: "operator", foreground: "ab5959" },
  { token: "tag", foreground: "1e754f" },
  { token: "comment", foreground: "a0ada0" },
  { token: "number", foreground: "2f798a" },
  { token: "regexp", foreground: "ab5e3f" },
  { token: "identifier", foreground: "b07d48" },
  { token: "function", foreground: "59873a" },
  { token: "markup.heading", foreground: "1e754f", fontStyle: "bold" },
  { token: "markup.raw", foreground: "1e754f" },
  { token: "markup.quote", foreground: "2e808f" },
  { token: "markup.italic", fontStyle: "italic" },
  { token: "markup.bold", fontStyle: "bold" },
];

const vitesseDarkRules: editor.ITokenThemeRule[] = [
  { token: "keyword.operator", foreground: "cb7676" },
  { token: "keyword", foreground: "4d9375" },
  { token: "constant.language.boolean", foreground: "4d9375" },
  { token: "constant.language", foreground: "4d9375" },
  { token: "constant.numeric", foreground: "4C9A91" },
  { token: "constant", foreground: "c99076" },
  { token: "string.regexp", foreground: "c4704f" },
  { token: "string.comment", foreground: "758575dd" },
  { token: "string", foreground: "c98a7d" },
  { token: "support.type.builtin", foreground: "cb7676" },
  { token: "support.type", foreground: "5DA994" },
  { token: "support.constant", foreground: "c99076" },
  { token: "support", foreground: "b8a965" },
  { token: "storage.type", foreground: "cb7676" },
  { token: "storage", foreground: "cb7676" },
  { token: "entity.name.function", foreground: "80a665" },
  { token: "entity.name.tag", foreground: "4d9375" },
  { token: "entity.name.type", foreground: "5DA994" },
  { token: "entity.name", foreground: "80a665" },
  { token: "entity.other.attribute-name", foreground: "bd976a" },
  { token: "variable.language", foreground: "c99076" },
  { token: "variable", foreground: "bd976a" },
  { token: "type.identifier", foreground: "6872ab" },
  { token: "type", foreground: "5DA994" },
  { token: "attribute.value", foreground: "c98a7d" },
  { token: "attribute.name", foreground: "b8a965" },
  { token: "meta.property-name", foreground: "b8a965" },
  { token: "meta.object-literal.key", foreground: "b8a965" },
  { token: "meta.module-reference", foreground: "4d9375" },
  { token: "property", foreground: "b8a965" },
  { token: "namespace", foreground: "db889a" },
  { token: "delimiter.bracket", foreground: "666666" },
  { token: "delimiter", foreground: "666666" },
  { token: "operator", foreground: "cb7676" },
  { token: "tag", foreground: "4d9375" },
  { token: "comment", foreground: "758575dd" },
  { token: "number", foreground: "4C9A91" },
  { token: "regexp", foreground: "c4704f" },
  { token: "identifier", foreground: "bd976a" },
  { token: "function", foreground: "80a665" },
  { token: "markup.heading", foreground: "4d9375", fontStyle: "bold" },
  { token: "markup.raw", foreground: "4d9375" },
  { token: "markup.quote", foreground: "5d99a9" },
  { token: "markup.italic", fontStyle: "italic" },
  { token: "markup.bold", fontStyle: "bold" },
];

const vitesseLightTheme: editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  colors: {
    "editor.background": "#ffffff",
    "editor.foreground": "#393a34",
    "editorLineNumber.foreground": "#393a3450",
    "editorLineNumber.activeForeground": "#4e4f47",
    "editor.lineHighlightBackground": "#f7f7f7",
    "editor.selectionBackground": "#4d937533",
    "editor.inactiveSelectionBackground": "#4d93751a",
    "editor.selectionHighlightBackground": "#4d93751a",
    "editor.foldBackground": "#4d93751a",
    "editorIndentGuide.background": "#00000015",
    "editorIndentGuide.activeBackground": "#00000030",
    "editorWhitespace.foreground": "#00000015",
    "editor.findMatchBackground": "#e6cc7744",
    "editor.findMatchHighlightBackground": "#e6cc7766",
    "editorBracketMatch.background": "#1c6b4820",
    "editor.wordHighlightBackground": "#1c6b4805",
    "editor.wordHighlightStrongBackground": "#1c6b4810",
    "editorWidget.background": "#ffffff",
    "editorStickyScroll.background": "#f7f7f7",
    "editorStickyScrollHover.background": "#f7f7f7",
  },
  rules: vitesseLightRules,
};

const vitesseDarkTheme: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  colors: {
    "editor.background": "#121212",
    "editor.foreground": "#dbd7caee",
    "editorLineNumber.foreground": "#dedcd550",
    "editorLineNumber.activeForeground": "#bfbaaa",
    "editor.lineHighlightBackground": "#181818",
    "editor.selectionBackground": "#4d937540",
    "editor.inactiveSelectionBackground": "#4d937520",
    "editor.selectionHighlightBackground": "#4d937520",
    "editor.foldBackground": "#4d937520",
    "editorIndentGuide.background": "#ffffff15",
    "editorIndentGuide.activeBackground": "#ffffff30",
    "editorWhitespace.foreground": "#ffffff15",
    "editor.findMatchBackground": "#e6cc7722",
    "editor.findMatchHighlightBackground": "#e6cc7744",
    "editorBracketMatch.background": "#4d937520",
    "editor.wordHighlightBackground": "#1c6b4805",
    "editor.wordHighlightStrongBackground": "#1c6b4810",
    "editorWidget.background": "#121212",
    "editorStickyScroll.background": "#181818",
    "editorStickyScrollHover.background": "#181818",
  },
  rules: vitesseDarkRules,
};

export function defineWorkspaceMonacoThemes(
  monaco: typeof import("monaco-editor"),
) {
  monaco.editor.defineTheme(workspaceMonacoThemeLight, vitesseLightTheme);
  monaco.editor.defineTheme(workspaceMonacoThemeDark, vitesseDarkTheme);
}
